language: python
python:
  - "2.7"
install:
  - "pip install -e .[tests]"
  - "pip install coveralls"
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - "coverage run --source=htetl setup.py nosetests"
  - coveralls
services:
  - postgresql
cache: pip
